const cardData = [
    { question: "¿Capital de Francia?", options: ["París", "Londres", "Roma", "Madrid"], correctIndex: 0 },
    { question: "¿País más poblado?", options: ["China", "India", "Estados Unidos", "Brasil"], correctIndex: 1 },
    { question: "¿Resultado de 8 × 7?", options: ["54", "56", "64", "49"], correctIndex: 1 },
    { question: "¿Símbolo químico O?", options: ["Oro", "Osmio", "Oxígeno", "Plata"], correctIndex: 2 },
    { question: "¿Continente de Egipto?", options: ["América", "Asia", "África", "Europa"], correctIndex: 2 },
    { question: "¿Número primo?", options: ["9", "15", "11", "21"], correctIndex: 2 },
    { question: "¿Océano con Europa?", options: ["Pacífico", "Atlántico", "Índico", "Ártico"], correctIndex: 1 },
    { question: "¿El planeta rojo?", options: ["Saturno", "Marte", "Júpiter", "Venus"], correctIndex: 1 },
    { question: "¿Capital de Japón?", options: ["Tokio", "Seúl", "Pekín", "Kioto"], correctIndex: 0 },
    { question: "¿Resultado de 9 + 9?", options: ["16", "18", "20", "81"], correctIndex: 1 },
    { question: "¿País de la torre Eiffel?", options: ["Italia", "Francia", "España", "Alemania"], correctIndex: 1 },
    { question: "¿Símbolo químico Au?", options: ["Plata", "Cobre", "Oro", "Hierro"], correctIndex: 2 },
    { question: "¿Capital de Italia?", options: ["Roma", "Milán", "Venecia", "Florencia"], correctIndex: 0 },
    { question: "¿Resultado de 100 ÷ 10?", options: ["1", "10", "100", "0"], correctIndex: 1 },
    { question: "¿País de las pirámides?", options: ["México", "Grecia", "Egipto", "Perú"], correctIndex: 2 },
    { question: "¿El satélite natural?", options: ["Sol", "Luna", "Marte", "Tierra"], correctIndex: 1 },
    { question: "¿Capital de España?", options: ["Madrid", "Barcelona", "Sevilla", "Valencia"], correctIndex: 0 },
    { question: "¿Resultado de 12 × 12?", options: ["124", "144", "134", "154"], correctIndex: 1 },
    { question: "¿Símbolo químico H?", options: ["Helio", "Hidrógeno", "Hierro", "Hafnio"], correctIndex: 1 },
    { question: "¿Capital de Alemania?", options: ["Berlín", "Múnich", "Hamburgo", "Fráncfort"], correctIndex: 0 },
    { question: "¿Resultado de 50 − 15?", options: ["25", "35", "45", "30"], correctIndex: 1 },
    { question: "¿País del tango?", options: ["Brasil", "Colombia", "Argentina", "Chile"], correctIndex: 2 },
    { question: "¿Símbolo químico Ag?", options: ["Oro", "Plata", "Argón", "Azufre"], correctIndex: 1 },
    { question: "¿Capital de Colombia?", options: ["Medellín", "Cali", "Bogotá", "Cartagena"], correctIndex: 2 },
    { question: "¿Resultado de 9 × 9?", options: ["81", "72", "99", "64"], correctIndex: 0 },
    { question: "¿País de los canguros?", options: ["Nueva Zelanda", "Sudáfrica", "Australia", "Canadá"], correctIndex: 2 },
    { question: "¿Símbolo químico C?", options: ["Calcio", "Carbono", "Cloro", "Cobalto"], correctIndex: 1 },
    { question: "¿Capital de México?", options: ["Guadalajara", "Monterrey", "Puebla", "México"], correctIndex: 3 },
    { question: "¿Resultado de 72 ÷ 8?", options: ["7", "8", "9", "6"], correctIndex: 2 },
    { question: "¿El mamífero volador?", options: ["Avestruz", "Pingüino", "Murciélago", "Ballena"], correctIndex: 2 }
];